config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :documents
  
  root to: 'documents#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  mount_uploader :first_image, ImageUploader
  mount_uploader :last_image, ImageUploader
  mount_uploaders :images, ImageUploader

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :documents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone, :office_phone])
  end
end

app/controllers/documents_controller.rb
require 'fastimage'
require 'aws-sdk'

class DocumentsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_document, only: [:show]

  def index # show all templates
    @documents = Document.where(user_id: current_user.id).order("CREATED_AT DESC")
  end

  def new
    @document = Document.new
  end
  
  def create
    new_document = Document.new(document_params)
    new_document.user_id = current_user.id

    new_document.save

    puts "--- Creating PDF"
    
    # Create PDF
    Prawn::Document.generate("public/pdfs/#{new_document.id}_#{new_document.customer_name}.pdf", :margin => 0) do
      # first page
      font_families.update("Calibri" => {
        :normal => "app/assets/fonts/Calibri.ttf"
      })

      font_size 16
      font "Calibri"
      fill_color "ffffff"

      # image "#{Rails.root}/app/assets/images/1.png", :at => [0, 792], :width => 612
      image "app/assets/images/1a.png", :at => [0, 792], :width => 612
      image open("#{new_document.first_image.url}"), :at => [0, 570], :width => 464, :height => 317

      draw_text "Willow Lane Cabinetry Room Design", :at => [20, 752], :size => 26
      draw_text "Designed For: #{new_document.customer_name}", :at => [20, 724]
      draw_text "Designed By: #{new_document.designer_name}", :at => [20, 702]
      draw_text "Finish Name: #{new_document.finish_name}", :at => [20, 680]
      draw_text "Designer Phone: #{new_document.designer_phone}", :at => [20, 658]
      draw_text "Office Phone: #{new_document.office_phone}", :at => [20, 636]
      draw_text "Designer Email: #{new_document.designer_email}", :at => [20, 614]
      draw_text "Date: #{new_document.date}", :at => [20, 592]

      # 2 ~ Custom pages
      if new_document.images.present?
        new_document.images.each do |img|
          start_new_page

          # header - 7c131d color changed for willow shop
          fill_color "2db3a2"
          fill_rectangle [0, 792], 612, 73

          # footer - 185471
          fill_color "222222"
          fill_rectangle [0, 53], 612, 53

          # restore color
          fill_color "ffffff"

          # fill image
          arr = FastImage.size("#{img.url}")
          aspect_ratio = [612.0 / arr[0], 666.0 / arr[1]].min
          width = arr[0] * aspect_ratio
          height = arr[1] * aspect_ratio

          image open("#{img.url}"), :at => [(612.0 - width) / 2, 719 - (666.0 - height) / 2], :width => width, :height => height
        end
      end

      # 3 ~ 12 pages
      for i in 3..12
        start_new_page
        image "app/assets/images/#{i}a.png", :at => [0, 792], :width => 612
      end
      # start_new_page
      # last page
      start_new_page
      image "app/assets/images/13a.png", :at => [0, 792], :width => 612
      image open("#{new_document.last_image.url}"), :at => [0, 720], :width => 612, :height => 373
    end
    puts "--- Ended"
    # image "#{Prawn::DATADIR}/images/pigs.jpg", :fit => [size, size]

    # Uploading to S3
    begin
      file_name = "#{new_document.id}_#{new_document.customer_name}.pdf"

      s3 = Aws::S3::Resource.new(region: ENV['AWS_REGION'])
      obj = s3.bucket(ENV['S3_PDF_BUCKET_NAME']).object(file_name)
      obj.upload_file("public/pdfs/#{new_document.id}_#{new_document.customer_name}.pdf", acl:'public-read')
      
      # Remove local file
      File.delete("public/pdfs/#{new_document.id}_#{new_document.customer_name}.pdf")
    rescue Aws::S3::Errors::ServiceError
    end

    redirect_to documents_path
  end

  def show
    redirect_to "https://s3.us-east-2.amazonaws.com/#{ENV['S3_PDF_BUCKET_NAME']}/#{@document.id}_#{@document.customer_name}.pdf"
  end

  private

  def document_params
    params.require(:document).permit(:customer_name, :designer_name, :finish_name, :designer_phone, :office_phone, :designer_email, :date, :first_image, :last_image, {images: []})
  end

  def set_document
    @document = Document.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def s3_url(doc)
    "https://s3.us-east-2.amazonaws.com/#{ENV['S3_PDF_BUCKET_NAME']}/#{doc.id}_#{doc.customer_name}.pdf"
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/documents/index.html.erb
<table class="table m-t-20" data-filtering="true" data-paging-size="12" data-paging="true">
  <thead>
    <tr>
      <th data-breakpoints="xs">ID</th>
      <th>Customer</th>
      <th>Designer</th>
      <th data-breakpoints="xs">Designer Email</th>
      <th data-breakpoints="xs sm">Date</th>
      <th data-breakpoints="xs sm md"></th>
    </tr>
  </thead>
  <tbody>
    <% @documents.each do |doc| %>
      <tr>
        <td> <%= doc.id %> </th>
        <td> <%= doc.customer_name %> </td>
        <td> <%= doc.designer_name %> </td>
        <td> <%= doc.designer_email %> </td>
        <td> <%= doc.date %> </td>
        <td> <%= link_to "View", s3_url(doc), target: "_blank", :class => "btn btn-xs btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<script type="text/javascript">
  var ready;

  ready = function() {

    $(function () {
      $('.table').footable();
    });

  };
  $(document).ready(ready);
  $(document).on('page:load', ready);
</script>

app/views/documents/new.html.erb
<div class="container">
  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog modal-sm">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-body text-center">
          <img src="<%= image_path('process_img.gif') %>">
        </div>
      </div>
      
    </div>
  </div>
  
</div>

<h1 class="text-center m-b-20">Create a new Document</h1>
<%= form_for @document do |f| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>Basic Information</h3>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-sm-6">
          <div class="form-group row">
            <%= f.label :customer_name, :class => 'col-sm-4 col-form-label' %>
            <div class="col-sm-8">
              <%= f.text_field :customer_name, :class => 'form-control col-sm-10', :required => true %>
            </div>
          </div>

          <div class="form-group row">
            <%= f.label :designer_name, :class => 'col-sm-4 col-form-label' %>
            <div class="col-sm-8">
              <%= f.text_field :designer_name, :value => current_user.name, :class => 'form-control col-sm-10', :required => true %>
            </div>
          </div>

          <div class="form-group row">
            <%= f.label :finish_name, :class => 'col-sm-4 col-form-label' %>
            <div class="col-sm-8">
              <%= f.text_field :finish_name, :class => 'form-control col-sm-10', :required => true %>
            </div>
          </div>

          <div class="form-group row">
            <%= f.label :designer_phone, :class => 'col-sm-4 col-form-label' %>
            <div class="col-sm-8">
              <%= f.text_field :designer_phone, :value => current_user.phone, :class => 'form-control col-sm-10', :required => true %>
            </div>
          </div>

          <div class="form-group row">
            <%= f.label :office_phone, :class => 'col-sm-4 col-form-label' %>
            <div class="col-sm-8">
              <%= f.text_field :office_phone, :value => current_user.office_phone, :class => 'form-control col-sm-10', :required => true %>
            </div>
          </div>

          <div class="form-group row">
            <%= f.label :designer_email, :class => 'col-sm-4 col-form-label' %>
            <div class="col-sm-8">
              <%= f.text_field :designer_email, :value => current_user.email, :class => 'form-control col-sm-10', :required => true %>
            </div>
          </div>

          <div class="form-group row">
            <%= f.label :date, :class => 'col-sm-4 col-form-label' %>
            <div class="col-sm-8">
              <%= f.text_field :date, :class => 'form-control col-sm-10 datepicker', :required => true %>
            </div>
          </div>
        </div>

        <div class="col-sm-6">
          <div class="form-group row">
            <%= f.label :image_for_the_first_page, :class => 'col-sm-6 col-form-label' %>
            <div class="col-sm-8">
              <%= f.file_field :first_image, :class => 'form-control col-sm-10', :required => true, :accept => "image/*" %>
            </div>
          </div>
          <div class="form-group row">
            <%= f.label :image_for_the_last_page, :class => 'col-sm-6 col-form-label' %> 
            <div class="col-sm-8">
              <%= f.file_field :last_image, :class => 'form-control col-sm-10', :required => true, :accept => "image/*" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>Custom pages</h3>
    </div>
    <div class="panel-body">
      <div class="wrapper">
        <div class="drop">
          <div class="cont">
            <i class="fa fa-cloud-upload"></i>
            <div class="tit">
              Drag & Drop
            </div>
            <div class="desc">
              your files to Assets, or 
            </div>
            <div class="browse">
              click here to browse
            </div>
          </div>
          <!-- <output id="list"></output> -->
          <input id="files" name="images" multiple="true" type="file" accept="image/*" style="z-index: 10000" />
        </div>
      </div>

      <ul id="sortable">
      </ul>


      <script type="text/javascript">
        // DatePicker
        $('.datepicker').datepicker(
          {
            format: 'mm/dd/yyyy',
            autoclose: true
          }
        );
        $('.datepicker').datepicker("setDate", new Date());

        // Drag and Drop
        var drop = $("#files");
        var file_list = [];

        drop.on('dragenter', function (e) {
          $(".drop").css({
            "border": "4px dashed #09f",
            "background": "rgba(0, 153, 255, .05)"
          });
          $(".cont").css({
            "color": "#09f"
          });
        }).on('dragleave dragend mouseout drop', function (e) {
          $(".drop").css({
            "border": "3px dashed #DADFE3",
            "background": "transparent"
          });
          $(".cont").css({
            "color": "#8E99A5"
          });
        });

        function handleFileSelect(evt) {
          var files = evt.target.files; // FileList object

          var list_obj = document.getElementById('sortable')
          // while (list_obj.firstChild) {
          //   list_obj.removeChild(list_obj.firstChild);
          // }

          // Loop through the FileList and render image files as thumbnails.
          // save previous length first
          var f_length = file_list.length;
          var pairObj = new Object();
          for (var i = 0, f; f = files[i]; i++) {
            // Only process image files.
            if (!f.type.match('image.*')) {
              continue;
            }

            file_list.push(f);
            pairObj[f] = i + f_length;

            // console.log(file_list.length);

            var reader = new FileReader();

            // Closure to capture the file information.
            reader.onload = (function(theFile) {
              var file_id_attr = pairObj[theFile];
              return function(e) {
                // Render thumbnail.
                var li = document.createElement('li');
                var close_btn = document.createElement('span');

                close_btn.className = 'close-btn';
                close_btn.onclick = function() {
                  list_obj.removeChild(li);
                }

                li.innerHTML = ['<img class="thumb" src="', e.target.result,
                                  '" title="', escape(theFile.name), '" file_id="', file_id_attr, '"/>'].join('');
                li.insertBefore(close_btn, null);
                list_obj.insertBefore(li, null);
              };
            })(f);

            // Read in the image file as a data URL.
            reader.readAsDataURL(f);
          }
        }
        $('#files').change(handleFileSelect);

        // Form submit
        $('.new_document').submit(function() {
          var formData = new FormData( this );
          var request = new XMLHttpRequest();
          request.open("POST", "/documents");

          // get all available sorted image list
          var nodes = document.getElementById('sortable').childNodes;

          for(i = 0; i < nodes.length; i ++)
          {
            if(nodes[i].firstChild != null) {
              file_id = parseInt(nodes[i].firstChild.getAttribute("file_id"), 10);
              formData.append("document[images][]", file_list[file_id]);
            }
          }
          request.send(formData);

          $('#myModal').modal();

          request.onload = function(oEvent) {
            if(request.status == 200) {
              // Success
              $('#myModal').modal('hide');
              window.location = '/';
            }
            else {
              // Failure
              $('#myModal').modal('hide');
              alert('Something went wrong! Please try again later.');
            }
          }
          return false;
        });
      </script>
    </div>
  </div>

  <%= f.submit "Submit", :class => 'btn btn-success m-b-20' %>
  <script type="text/javascript">
    $( function() {
      $( "#sortable" ).sortable();
      $( "#sortable" ).disableSelection();
    } );
  </script>
<% end %>

app/views/home/index.html.erb
Welcome!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TylerWillow</title>
    <%= csrf_meta_tags %>
    <script src="https://blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js"></script>
    <!-- The Canvas to Blob plugin is included for image resizing functionality -->
    <script src="https://blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js"></script>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container-fluid">
    <% if current_user.present? %>
      <%= render partial: 'shared/header' %>
    <% end %>
    
    <div class="container">
      <div class="row">
        <% if notice %>
          <p class="notice"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert"><%= alert %></p>
        <% end %>
      </div>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<div class="header-panel">
  <div>
    <span><%= current_user.email %></span>
    <%= link_to "Create", new_document_path %>
    <%= link_to "Browse", root_path %>
    <% if current_user.is_admin == true %>
      <%= link_to "Admin", rails_admin_path %>
    <% end %>
  </div>

  <div>
    <%= link_to "SignOut", destroy_user_session_path, method: :delete %>
  </div>
</div>